### ISSUE TITLE
Add how to switch to a different "locale" in the README ?

### ISSUE THREAD

**Issue by thomas-genet** [anders94/blockchain-demo#101]
Dear Anders, 

Thank you for this very nice demo of blockchains!

However, I am new to Javascript and having difficulty in switching the demo to a different language, though it seems to be part of the applications.

Could you add the instructions in the manual?

Thanks in advance, 

Thomas

**Comment by anders94** [comment]
It should switch based on the browser locale setting. Check to make sure the browser you are using is set to a locale supported by the codebase. These are currently supported: https://github.com/anders94/blockchain-demo/tree/master/locales
