### ISSUE TITLE
Changing block's data also changes next block's previous hash

### ISSUE THREAD

**Issue by AkashKarnatak** [anders94/blockchain-demo#106]
If I tamper block 4's data then it's hash will change. But why does block 5's previous hash gets affected?
![Screenshot 2022-10-14 at 21-34-08 Blockchain Demo](https://user-images.githubusercontent.com/54985621/195891430-4c702872-fa9b-4097-bff5-22fbed1e8d0c.png)

I expect it to remain the same like so.
![Screenshot 2022-10-14 at 21-38-48 Blockchain Demo](https://user-images.githubusercontent.com/54985621/195892176-5dab585b-5681-40d9-b33c-adbfb73318d9.png)

**Comment by anders94** [comment]
This is expected behavior. The previous hash is calculated from the previous block, not something set by that block. If it doesn't change then there is no integrity guarantee being established and the usefulness of a blockchain disappears.
