### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PankajSinghV** [anders94/blockchain-demo#11]
The file is not working at localhost:3000.

**Comment by anders94** [comment]
Do you have any more info about this? Do you have the server running? What output do you see when you launch the server?

**Comment by AbhijeetNagawade** [comment]
$ ./bin/www
module.js:328
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/abhijeet/blockchain-demo/app.js:1:77)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)

**Comment by anders94** [comment]
Did you
```
npm install
```
first?

**Comment by AbhijeetNagawade** [comment]
Thank you for the reply @anders94 

Yes, I did 'npm install'

but on running server it gave error as 
/usr/bin/env: node: No such file or directory

so I googled and found out symlink solves it
ln -s /usr/bin/nodejs /usr/bin/node

upon symlinking when I tried running server it gave me error as per the earlier post.

**Comment by anders94** [comment]
When you say you did
```nom install```
did that complete with no errors?

If you didn't get errors and you now have a `node_modules/` directory in the distribution directory, try reinstalling node.js. I'm not convinced the `npm` binary fits with the `node` binary you are using.

**Comment by AbhijeetNagawade** [comment]
tried reinstalling nodejs it said nodejs is uptodate
reinstalled npm
now blockchain demo is working
Thank you very much @anders94

**Comment by anders94** [comment]
:+1:

**Comment by Omkaragrawal** [comment]
![image](https://user-images.githubusercontent.com/10913160/28643305-0b0e3600-7273-11e7-8c1d-cb1a7a298252.png)
Sir I tried accessing http://localhost:3000/ but the server was hosted on 8080. Then I tried giving it a port, but in both methods the www file is getting downloaded.
![image](https://user-images.githubusercontent.com/10913160/28643320-174cb16c-7273-11e7-899a-1e11a42717cf.png)
This is what I have in directory. npm -install was completed successfully without any errors but still it is not working.
After all of the above I tried (docker -compose up -d) but it gives error in this process as below.
![image](https://user-images.githubusercontent.com/10913160/28643373-452b62f4-7273-11e7-90cb-4f596eb03caf.png)

**Comment by scriptArchitect** [comment]
Hi,

Do you have the docker-compose installed. If not can you update your docker or install docker-compose command and try again?

https://docs.docker.com/compose/install/

It works for me with

docker-compose up -d

**Comment by Omkaragrawal** [comment]
For the installer package it says that it does not support your processor type. While I tried doing this:

> npm install docker-compose -g

it installs something but afterward gives error showing that there is no command as docker-compose.

**Comment by RubeRad** [comment]
I had a similar problem. I was running with a version that I modified to have adjustable hash strength (at a finer resolution than entire hex digits at 16x difficulty per additional digit -- I would be happy to share this change with you).

I was able to see the page in my own browser using either localhost:3000 or <ipaddress>:3000, but my students could not see anything at <ipaddress>:3000. I tried switching my laptop out of the staff wifi, over to the student wifi, but it didn't help.

I had previously run a successful test with a colleague being able to load from <ipaddress>:3000, I'm not sure what went wrong today.

fyi my laptop is Ubuntu 20.4 and my two students both had macs.

**Comment by anders94** [comment]
You will have to replace `localhost` with the IP of your laptop and make sure your users can directly reach that IP. Take a look at your network settings and replace `localhost` with whatever your network address is. (usually something like `192.168.1.2` or `10.0.02`)

**Comment by RubeRad** [comment]
yes that's what I mean _ipaddress_:3000. I was able to see it but others were not (today -- a while ago when I tested, somebody else was successful in browsing to _ipaddress_:3000 when I had npm running). 

I'm not sure if they were able to 'see' my IP apart from not being able to browse to the URL, I didn't have time in class to investigate. 

My laptop is shut down now, but would npm have logs I might be able to search through? Look for evidence of students trying and failing to connect, maybe some helpful error messages?

**Comment by anders94** [comment]
Yeah, make sure you are on the same WiFi network and you could try to ping the other machine from the terminal:
```
ping -c 1 192.168.1.1`
```
If you see something like this, you are good:
```
PING 192.168.1.1 (192.168.1.1): 56 data bytes
64 bytes from 192.168.1.1: icmp_seq=0 ttl=64 time=4.715 ms

--- 192.168.1.1 ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 4.715/4.715/4.715/0.000 ms
```
Then try a web browser on `http://192.168.1.1:3000`. (replace with your IP)

You need to be running the app - `npm start` does that so you need to have that going when others load the site.

There are no logs from `rpm` apart from the ones you see in the terminal. But the stuff there should give you hints as to things working or not and why.

**Comment by RubeRad** [comment]
thx, I think I got all those things working when I successfully tested with a colleague a while ago. Trying to remember everything, there's a slight chance I forgot to restart npm after I switched from Staff wifi, to the Student wifi that their laptops were on.

Thx for the tips, the moment is passed for this year, but next year I'll be sure to do some earlier pre-trials with students before the actual day.

Do you want the finer-resolution hash-strength changes? They are of the form
majorDifficulty=4; // how many 0 are required in the front of the hash
minorDifficulty=7; // max value of next hex digit

with a handful of other lines modified to use those together.

**Comment by RubeRad** [comment]
I tried again this morning before class, bringing my own separate laptop, putting them both onto the same student wifi network, and the other laptop could not even ping the npm laptop. I suspect they've got some kind of setup in the student wifi to isolate all computers from each other, probably to prevent student hijinx
