### ISSUE TITLE
Blockhash on tokens.html unaffected by changes to first transaction.

### ISSUE THREAD

**Issue by dstadulis** [anders94/blockchain-demo#14]
Observed behavior:
The blockhash of any block on the tokens.html page is unaffected by changes to the first transaction (the top most transaction) in any block.

To reproduce:
Load https://anders.com/blockchain/tokens.html
Modify the tx value or sender or receiver, for the first transaction (the top most transaction) in the block.

Expected result:
Any modification to any data in the block should cause the Blockhash to change.
Block color with a modified tx, and the dependent blocks, should turn red until mined again.

P.S.
Thanks so much for this wonderful demonstration.

**Comment by anders94** [comment]
Thanks - should be fixed now.

**Comment by dstadulis** [comment]
Expected result now occurs.

You're fast, Anders!  Thanks again for the demonstration tool
