### ISSUE TITLE
Coinbase mining changes data instead of nonce

### ISSUE THREAD

**Issue by Aluriak** [anders94/blockchain-demo#2]
Hi !

This work is a amazing idea :)

I'm struggling with the coinbase tab. I change, for instance, the initial amount of coin received by Anders. As the block chain is broken, i click *Mine*, and, instead of modifying the *nonce* value, the initial amount of coin is reset to 100.

IMHO, it should be much more interesting to only tweak *nonce* value (as shown in the video),
allowing one to break the blockchain to understand its interest in case of coinbase implementation.

Tested on Firefox 51.0.1, 64bits, fedora 24.

**Comment by dhruvdutt** [comment]
It's working fine for me.

**Comment by tunghim** [comment]
I have tested on Chrome, Firefox and Safari. The issue only appears in Firefox. If there is one thing that separates Firefox from other browsers, that would be the rendering engine Gecko I guess.

**Comment by anders94** [comment]
There was an issue with the mining button reloading the page in some browsers. I just merged a fix for that. Please let me know if this is still happening for you.

**Comment by Aluriak** [comment]
Mining seems to work properly now !

Thank you !
