### ISSUE TITLE
Error running in container

### ISSUE THREAD

**Issue by kpantos** [anders94/blockchain-demo#22]
I'm getting the following error wher trying to run the demo in a container using `docker-compose up -d` command 
`': No such file or directory`
Is it working for you?
Thanks.

**Comment by abitrolly** [comment]
Works fine.

**Comment by anders94** [comment]
Works for me as well. Are you still having this issue?

**Comment by kpantos** [comment]
Yes, I'm still getting the same issue.
Running docker for windows on Windows 10.

**Comment by abitrolly** [comment]
@kpantos does `docker-compose` work on your system? Can you pass any tutorial with it?

**Comment by anders94** [comment]
Closing this as there hasn't been a response in quite a while.
