### ISSUE TITLE
Kindly implement timestamp

### ISSUE THREAD

**Issue by DineshDevaraj** [anders94/blockchain-demo#27]

**Comment by anders94** [comment]
Timestamp on blocks? It might be a little confusing to add something not critical to understanding the concept. Am I understanding your question?

**Comment by prahaladbelavadi** [comment]
@DineshDevaraj Do you mean something similar to [Open time stamps](https://opentimestamps.org/) ?

**Comment by anders94** [comment]
Closing this as there hasn't been a response in quite a while.
