### ISSUE TITLE
How do you run this demo on Windows?

### ISSUE THREAD

**Issue by RumenLazarov** [anders94/blockchain-demo#28]
Hi Anders, 

Great demo software on blockchain! Thank you for creating and sharing it!

This is not an issue but a question on the installation instructions. How could one run this application on Windows machine using Internet Information Service (IIS) or using XAMPP? I am not very technical, so apologies for what might be a simple question. 

Also, would it be possible for other users on their separate machines to connect to the demo application and simultaneously update the blockchain? That is if one is able to run the application on a local host and having users connect and update their blockchains. 

Thanks again and all the best,
Rumen

**Comment by abitrolly** [comment]
Windows 10 can run Linux, so why not try it? https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by prahaladbelavadi** [comment]
@RumenLazarov I've made a couple of changes to make slightly user friendly.

- Install Nodejs and npm from [here](https://nodejs.org/en/)
- Clone the [repo](https://github.com/prahaladbelavadi/blockchain-demo) 
```
git clone https://github.com/prahaladbelavadi/blockchain-demo
```
-  Navigate into the repo
```
cd ./blockchain-demo
```
- install npm dependencies
```
npm install
```
- Start the node server
 ```
node ./bin/blockchain-demo.js
```
