### ISSUE TITLE
Highlight coinbase repartition problem

### ISSUE THREAD

**Issue by Aluriak** [anders94/blockchain-demo#3]
Hi !

What about display a color when a verified blockchain as a coin repartition problem ?
For instance, if Anders initially receive only 10 coin, the second block (and therefore the next ones) should be marked as *suspect* (with a yellow/orange color ?), because Anders gives money he doesn't have.

Even if this is out of scope of the blockchain implementation, it could be an easy way to teach about exchange verification using blockchains.

Maybe another tab, in order to keep things simple ?

**Comment by anders94** [comment]
Yeah, not a bad idea. I think there are many questions that come up that could benefit from visual explanations like this but I won't have time to do them all. Please feel free to fork the project and add stuff like this!
