### ISSUE TITLE
Unconfirmed Transaction / Mempool demo

### ISSUE THREAD

**Issue by taha-abbasi** [anders94/blockchain-demo#36]
It would be nice to demonstrate How 

- Transactions are added to the Mempool
- How miners pull from the pool
- How do miners broadcast to the network and update other nodes once they win the race to mine a block.

I found a simple demo and explanation here:
[https://99bitcoins.com/what-is-bitcoin-mempool/](https://99bitcoins.com/what-is-bitcoin-mempool/)

NOTE: The above link is just a reference to an attempt to tackle these questions, I think your solution can implement it in a much better manner.

These are some of the common requests I am seeing from folks that I am sharing the demo with. 

What are your thoughts? If you like this direction, I can contribute to the effort as well.

**Comment by anders94** [comment]
Yeah, that would be a great demo. I don't want to try to force it into this one though. I think it makes sense as a demo focused on that specifically - similar to how my public / private key demo relates to this demo. https://github.com/anders94/public-private-key-demo
