### ISSUE TITLE
Run the Blockchain-Demo on Wordpress

### ISSUE THREAD

**Issue by xr3rebell** [anders94/blockchain-demo#45]
Hello everyone,

I want to run this blockchain demo on my Wordpress page. There is no better way to explain how to start a blockchain.

Is it possible to get a small manual here? I have a complete web hosting with mysql and ftp access. Thank you for your help!

Is it possible to donate ETH instead of BTC?

greeting
xr3rebel

**Comment by anders94** [comment]
Hey - the demo is actually completely flat (no server component needs to be running) so in theory it can run on Wordpress or any other back-end technology without modification. The easiest way to do this is either save a working copy from the net somewhere (https://anders.com/blockchain/ is one location) or run it yourself and download a copy of the HTML, CSS and JavaScript files that way. Upload that to your WordPress and you should be good.

I have both BTC and ETH donation addresses on the YouTube video here https://www.youtube.com/watch?v=_160oMzblY8 but I'll add that to the README.md as well. Thanks for the note!
