### ISSUE TITLE
Change to a different block hashing algorithm?

### ISSUE THREAD

**Issue by ETN-A** [anders94/blockchain-demo#47]
Just emailed you only to find this here... This demo is superb and just wondering please (sadly not being savvy enough) whether it would take much to modify this to work with/appear to work with a different hashing algorithm: more specifically with [CryptoNight](https://cryptonote.org/cns/cns008.txt) for ed purposes?

**Comment by anders94** [comment]
yeah, that theoretically would be as easy as swapping out https://github.com/anders94/blockchain-demo/blob/master/public/javascripts/lib/sha256.js with an equivalent CryptoNight JavaScript implementation. Having not researched to see if such a thing exists, I don't know how much work this would actually be.

**Comment by ETN-A** [comment]
Ok, thank you for the response and will carry on "digging"... And thank you once again for the superb demos!
