### ISSUE TITLE
potential double-spending?

### ISSUE THREAD

**Issue by zeeqy** [anders94/blockchain-demo#50]
Thanks for making this wonderful demo.

I have a question about how to prevent double-spending.

In [coinbase](https://anders.com/blockchain/coinbase.html) block #5, if I change the first transaction to "$2000.00 from Jackson to Alexander", it will pass at nonce=10042. Since Jackson does not have 2000, do we have a double-spending issue here?

**Comment by anders94** [comment]
No, because the other peers don't agree on the final block's hash.
