### ISSUE TITLE
Unable to run the project on Windows 10  home 64 bit 

### ISSUE THREAD

**Issue by seetaramnt** [anders94/blockchain-demo#53]
I am trying to run this project on Windows 10 home 64 bit version with node js version v8.11.3 and npm version 5.6.0. I can install the packages using npm install and when run using npm start, it shows one message 
> blockchain-demo@0.0.1 start C:\test\blockchain-demo-master
> node ./bin/www
it hangs here and nothing works.
I tried with npm start --inspect option but the same behaviour is observed.

I tried on windows 7 32 bit OS with node version 8.x.x, it doesn't work. 
I remember that it was working with older version of node on windows 7 32 bit.

Please suggest.

**Comment by anders94** [comment]
It is supposed to "hang" there. What it is doing is running a web server on your local computer that you should be able to see at `http://localhost:3000`. Does that not work for you?

**Comment by anders94** [comment]
Closing this due to no response.
