### ISSUE TITLE
find a bug

### ISSUE THREAD

**Issue by TheStarBoys** [anders94/blockchain-demo#67]
In the coinbase option,Account transfers can be larger than UTXO.
![QQ截图20190527155400](https://user-images.githubusercontent.com/41286328/58404463-bf55d080-8097-11e9-9f9b-0b659a3471c8.png)

**Comment by anders94** [comment]
Thanks. I think of this more like a nice feature to have than a bug - the code does not check for this although it would be nice if it did. Please feel free to submit a PR to add that functionality.
