### ISSUE TITLE
npm start stuck and not doing anything

### ISSUE THREAD

**Issue by nadac5505** [anders94/blockchain-demo#73]
STUDENTS+CH590@DESKTOP-N MINGW64 ~
$ cd blockchain-demo

STUDENTS+CH590@DESKTOP-N MINGW64 ~/blockchain-demo (master)
$ npm install

> typechecker@2.0.8 preinstall C:\Users\CH590\blockchain-demo\node_modules\extendr\node_modules\typechecker
> node ./cyclic.js

> typechecker@2.0.8 preinstall C:\Users\CH590\blockchain-demo\node_modules\extract-opts\node_modules\typechecker
> node ./cyclic.js

> core-js@2.6.9 postinstall C:\Users\CH590\blockchain-demo\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

added 169 packages from 209 contributors and audited 350 packages in 57.359s
found 0 vulnerabilities

STUDENTS+CH590@DESKTOP-N MINGW64 ~/blockchain-demo (master)
$ npm start

> blockchain-demo@0.0.1 start C:\Users\CH590\blockchain-demo
> node ./bin/www

**Comment by anders94** [comment]
It is up and running - point a browser at http://localhost:3000
