### ISSUE TITLE
Error i18n and RUN app.js

### ISSUE THREAD

**Issue by yordanjose** [anders94/blockchain-demo#75]
** RUN app.js **
myuserpc@myuserpc-pc:~/Documentos/blockchain-demo$ node app.js 
module.js:549
    throw err;
    ^

Error: Cannot find module 'i18n'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/myuserpc/Documentos/blockchain-demo/app.js:2:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

** INSTALL i18n **
myuserpc@myuserpc-pc:~/Documentos/blockchain-demo$ npm install i18n --save
npm ERR! Linux 4.15.0-20-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "i18n" "--save"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/myuserpc/Documentos/blockchain-demo/npm-debug.log

**Comment by anders94** [comment]
Install the dependancies:
```npm install```
(of which `i18n` is one) and then start with:
```npm start```

**Comment by yordanjose** [comment]
In order for it to work I had to:
1. remove the "i18n" module from app.js
2. Install the "async" module, npm and async --save
3. Install the "debug" module, npm and debug --save
4. Install the "pug" module, npm i pug --save
5. Delete "__" in layout.pug and all files containing it, example [label.col-sm-2.control-label (for = 'hash') # {__ ('Hash')}]
