### ISSUE TITLE
app.js is not running

### ISSUE THREAD

**Issue by yordanjose** [anders94/blockchain-demo#76]
As i18n does not work, I have commented on it in the app.js file, but when executing the program with the node app.js. Nothing happens, just app.js seems not to be running on the server.

var express = require('express');
//var i18n = require('i18n');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

** next section **
/*i18n.configure({
  locales:['en', 'de', 'es', 'fr-CA', 'hi', 'ja', 'ko', 'nl', 'pl', 'pt', 'zh-CN', 'hu'],  
directory: __dirname + '/locales'
});*/

**Comment by anders94** [comment]
app.js isn't supposed to be run directly - rather `./bin/www` or better yet, just use:
```nom start```

**Comment by yordanjose** [comment]
In order for it to work I had to:
1. remove the "i18n" module from app.js
2. Install the "async" module, npm and async --save
3. Install the "debug" module, npm and debug --save
4. Install the "pug" module, npm i pug --save
5. Delete "__" in layout.pug and all files containing it, example [label.col-sm-2.control-label (for = 'hash') # {__ ('Hash')}]
