### ISSUE TITLE
Docker Container not running

### ISSUE THREAD

**Issue by dekre** [anders94/blockchain-demo#85]
Hi,

When running the container the following error occurs: `': No such file or directory`. But you can fix that by replacing `CMD        ["bin/www"]` with `CMD        ["node","./bin/www"]` inside the Dockerfile.

**Comment by abitrolly** [comment]
@dekre you can propose a PR by editing the Dockerfile online https://github.com/anders94/blockchain-demo/edit/master/Dockerfile
