### ISSUE TITLE
Pasting Values Does Not Immediately Change the Other Blocks

### ISSUE THREAD

**Issue by SamHartIvy** [anders94/blockchain-demo#96]
As the title states, there is a problem when pasting values in the Block, Blockchain, and Distributed tabs (the tabs I've been working with). This problem seems to be the case only for when a paste is used through right-click. This problem was tested on both the latest versions of Chrome and Firefox. This seems to be a simple fix as you can type something on the keyboard and backspace giving the correct result, but this is nonetheless something that could be fixed.

**Comment by anders94** [comment]
Good catch - I can work on a fix.

**Comment by anders94** [comment]
PR https://github.com/anders94/blockchain-demo/pull/97 should fix this. I'll merge once I've had a chance to test a bit more thoroughly.

**Comment by anders94** [comment]
OK, this PR is merged. Reopen an issue if you still find problems.
